name: "Airline Request: Soaring Symbols"
description: Request to add a new airline icon or update an existing one, strictly from official brand sources.
title: "Airline: Name of Airline (e.g., Vietnam Airlines)"
labels: ["airline-icon", "asset-request", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the Soaring Symbols airline library! **We only accept icons/logos sourced directly from the airline's official brand assets.**

        Please fill out the form below with the required information.

  - type: dropdown
    id: request_type
    attributes:
      label: Request Type
      description: Is this a new airline icon/logo or an update to an existing one? (Please apply the corresponding label to this issue.)
      options:
        - "New Airline Logo (Label: asset-new)"
        - "Update Existing Airline Logo (Label: asset-update)"
    validations:
      required: true
      
  - type: input
    id: airline_name
    attributes:
      label: Full Airline Name
      description: The official name of the airline.
      placeholder: e.g., Vietnam Airlines
    validations:
      required: true
      
  - type: textarea
    id: change_description
    attributes:
      label: 📝 If Updating, Describe the Change (Required for Updates)
      description: If this is an update request, briefly explain what changed (e.g., "The official color was changed from blue to dark navy" or "The font/wordmark has been updated."). Leave blank if adding a new logo.
      placeholder: e.g., The airline underwent a rebrand in 2023, changing the shade of green and simplifying the Golden Lotus design.

  - type: input
    id: official_website_link
    attributes:
      label: Official Airline Website Link
      description: The main URL for the airline's website. This is required for validation.
      placeholder: https://www.vietnamairlines.com/

  - type: textarea
    id: source_file_link
    attributes:
      label: Direct Link to SVG File or Brand/Press Kit Page
      description: |
        **Crucial:** Provide the direct URL to the SVG file, or a specific **brand guideline** or **press kit** page on the official website. **Do NOT use non-official sources.**
        - If linking to a brand/press kit page, ensure it contains a downloadable SVG file.
        - If the SVG is not available, provide a high-quality PNG or JPG link, but note that vectorization may be needed.
        - If the airline does not provide an SVG, please manually apply the **needs-vectorization** label to this issue.
      placeholder: |
        https://www.airline.com/assets/logo.svg
        OR
        https://www.airline.com/about/brand-guide-download-page
    # validations:
    #   required: true
      
  - type: checkboxes
    id: vector_status
    attributes:
      label: Vector File Status
      options:
        - label: SVG file is **NOT** provided in the link above. (Please manually apply the **needs-vectorization** label.)
