# blank_issues_enabled: false
contact_links:
  - name: "GitHub Discussions"
    url: "https://github.com/anhthang/soaring-symbols/discussions"
    about: "For questions, suggestions, or general discussions about Soaring Symbols."
