name: "Update Existing Airline"
description: Request to update an existing airline icon, logo, or related information (e.g., color, design change).
title: "Update: [Name of Airline] (e.g., Vietnam Airlines)"
labels: ["update airline"]
body:
  - type: markdown
    attributes:
      value: |
        This form is for requesting **UPDATES** to existing assets. Please be precise about the changes and provide the latest official source.
  
  - type: input
    id: airline_name
    attributes:
      label: Full Airline Name
      description: The official name of the airline whose asset needs updating.
      placeholder: e.g., Vietnam Airlines
    validations:
      required: true

  - type: textarea
    id: change_description
    attributes:
      label: 📝 Describe the Change
      description: |
        **Required:** Clearly explain what has changed.
      placeholder: e.g., Airline underwent a 2024 rebrand, changing the tail fin design and color palette.
    validations:
      required: true

  - type: input
    id: official_website_link
    attributes:
      label: Official Airline Website Link
      description: The main URL for the airline's website. Required for validation.
      placeholder: https://www.vietnamairlines.com/

  - type: textarea
    id: source_file_link
    attributes:
      label: Direct Link to NEW SVG File or Brand/Press Kit Page
      description: Provide the direct URL to the **updated** SVG file or the official brand page showing the new design.
      placeholder: |
        https://www.airline.com/assets/new-logo.svg
        OR
        https://www.airline.com/about/2024-brand-guide
    validations:
      required: false
